INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'BRAZIL', 'RIO DE JANEIRO') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM DESTINATION WHERE COUNTRY = 'BRAZIL' AND CITY = 'RIO DE JANEIRO');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'USA', 'NEW YORK') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'USA' AND CITY = 'NEW YORK');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'FRANCE', 'PARIS') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'FRANCE' AND CITY = 'PARIS');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'JAPAN', 'TOKYO') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'JAPAN' AND CITY = 'TOKYO');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'CANADA', 'TORONTO') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'CANADA' AND CITY = 'TORONTO');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'AUSTRALIA', 'SYDNEY') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'AUSTRALIA' AND CITY = 'SYDNEY');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'ITALY', 'ROME') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'ITALY' AND CITY = 'ROME');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'GERMANY', 'BERLIN') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'GERMANY' AND CITY = 'BERLIN');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'SPAIN', 'MADRID') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'SPAIN' AND CITY = 'MADRID');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'RUSSIA', 'MOSCOW') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'RUSSIA' AND CITY = 'MOSCOW');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'INDIA', 'DELHI') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'INDIA' AND CITY = 'DELHI');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'CHINA', 'BEIJING') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'CHINA' AND CITY = 'BEIJING');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'UK', 'LONDON') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'UK' AND CITY = 'LONDON');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'PORTUGAL', 'LISBON') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'PORTUGAL' AND CITY = 'LISBON');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'MEXICO', 'MEXICO CITY') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'MEXICO' AND CITY = 'MEXICO CITY');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'ARGENTINA', 'BUENOS AIRES') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM DESTINATION WHERE COUNTRY = 'ARGENTINA' AND CITY = 'BUENOS AIRES');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'SOUTH AFRICA', 'CAPE TOWN') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM DESTINATION WHERE COUNTRY = 'SOUTH AFRICA' AND CITY = 'CAPE TOWN');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'TURKEY', 'ISTANBUL') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'TURKEY' AND CITY = 'ISTANBUL');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'THAILAND', 'BANGKOK') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'THAILAND' AND CITY = 'BANGKOK');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'UAE', 'DUBAI') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'UAE' AND CITY = 'DUBAI');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'SOUTH KOREA', 'SEOUL') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'SOUTH KOREA' AND CITY = 'SEOUL');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'NEW ZEALAND', 'AUCKLAND') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM DESTINATION WHERE COUNTRY = 'NEW ZEALAND' AND CITY = 'AUCKLAND');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'SWEDEN', 'STOCKHOLM') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'SWEDEN' AND CITY = 'STOCKHOLM');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'SWITZERLAND', 'ZURICH') AS tmp
WHERE NOT EXISTS (SELECT 1
                  FROM DESTINATION
                  WHERE COUNTRY = 'SWITZERLAND' AND CITY = 'ZURICH');

INSERT INTO DESTINATION (COUNTRY, CITY)
SELECT *
FROM (SELECT 'NETHERLANDS', 'AMSTERDAM') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM DESTINATION WHERE COUNTRY = 'NETHERLANDS' AND CITY = 'AMSTERDAM');

INSERT INTO FLIGHT (ID, FLIGHT_NUMBER, DEPARTURE_DATE_TIME, ARRIVAL_DATE_TIME, ORIGIN, PRICE, DESTINATION_ID)
VALUES (RANDOM_UUID(), 'AZ123', '2024-12-17 08:00:00', '2024-12-17 12:00:00', 'Recife', 240.00,
        (SELECT ID FROM DESTINATION WHERE CITY = 'São Raimundo Nonato')),
       (RANDOM_UUID(), 'AZ200', '2024-12-18 10:00:00', '2024-12-18 14:00:00', 'Florianópolis', 606.00,
        (SELECT ID FROM DESTINATION WHERE CITY = 'Assunção')),
       (RANDOM_UUID(), 'AZ300', '2024-12-16 09:00:00', '2024-12-16 13:00:00', 'Florianópolis', 692.00,
        (SELECT ID FROM DESTINATION WHERE CITY = 'Montevidéu')),
       (RANDOM_UUID(), 'JS400', '2024-12-04 08:00:00', '2024-12-04 12:00:00', 'São Paulo', 726.00,
        (SELECT ID FROM DESTINATION WHERE CITY = 'Santiago')),
       (RANDOM_UUID(), 'GOL500', '2024-01-30 08:00:00', '2024-01-30 12:00:00', 'São Paulo', 974.00,
        (SELECT ID FROM DESTINATION WHERE CITY = 'Santa Cruz de la Sierra')),
       (RANDOM_UUID(), 'JS600', '2024-12-16 08:00:00', '2024-12-16 12:00:00', 'Florianópolis', 1313.00,
        (SELECT ID FROM DESTINATION WHERE CITY = 'Buenos Aires'));